
#pragma once
#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYERS_RETAIN_VAL

#define TAPPING_TERM 175

#undef RGBLIGHT_EFFECT_RAINBOW
#undef RGBLIGHT_EFFECT_SWIRL
#undef RGBLIGHT_EFFECT_SNAKE
#undef RGBLIGHT_EFFECT_KNIGHT
#undef RGBLIGHT_EFFECT_XMAS
#undef RGBLIGHT_EFFECT_GRADIENT
#undef RGBLIGHT_EFFECT_RGBTEST
#undef RGBLIGHT_EFFECT_TWINKLE
